name: CI Pipeline

on:
  pull_request:
    types: [opened, synchronize, closed, reopened]
    
permissions:
  pull-requests: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
jobs:
  pr_opened:
    if: github.event.action == 'opened'
    name: Comment on PR opened
    runs-on: ubuntu-latest
    env:
      PR_URL: ${{ github.event.pull_request.html_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add comment to PR
        run: gh pr comment "$PR_URL" --body "You have successfully opened a PR. Ensure you get at least one approval and all the tests pass before merging."

  pr_updated:
    if: github.event.action == 'synchronize'
    name: Comment on PR update
    runs-on: ubuntu-latest
    env:
       PR_URL: ${{ github.event.pull_request.html_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add comment to PR
        run:  gh pr comment "$PR_URL" --body "You have successfully updated this PR. Please ensure again that you get at least one approval and all the tests pass before merging."

  pr_closed:
    if: github.event.action == 'closed'
    name: Comment on PR closed
    runs-on: ubuntu-latest
    env:
       PR_URL: ${{ github.event.pull_request.html_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add comment to PR
        run: gh pr comment "$PR_URL" --body "You have successfully closed this PR. Please add a comment motivating your decision."

  pr_reopened:
    if: github.event.action == 'reopened'
    name: Comment on PR reopen
    runs-on: ubuntu-latest
    env:
      PR_URL: ${{ github.event.pull_request.html_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add comment to PR
        run: gh pr comment "$PR_URL" --body "You have successfully reopened this PR. Please add a comment motivating your decision."

        
   
     
     
